# Use postgres/postgres for postgres credentials: DATABASE_URL=postgres://postgres:postgres@127.0.0.1:5432/postgres
version: "3.1"

services:
  postgres:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST: localhost

    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
